version: "2"
services:

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      # to expose chrome VNC Viewer on port 5901
      - "5901:5900"

  firefox:
    # image 'selenium/node-firefox-debug' est... boguée...
    image: travix/selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      # to expose firefox VNC Viewer on port 5902
      - "5902:5900"
